// DO NOT EDIT. generated by webtyp.com/ormc

package devbrowser

import (
	"webtyp.com/model"
)

type ScreenshotArgs struct {
	Fullpage bool
}

func (m *ScreenshotArgs) ModelName() string { return "screenshot_args" }

func (m *ScreenshotArgs) Schema() []model.Field { return ScreenshotArgsModel.Fields }

func (m *ScreenshotArgs) Pointers() []any { return []any{&m.Fullpage} }

func (m *ScreenshotArgs) IsNil() bool { return m == nil }

func (m *ScreenshotArgs) EncodeFields(w model.FieldWriter) {
	w.Bool("fullpage", m.Fullpage)
}

func (m *ScreenshotArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.Bool("fullpage"); ok { m.Fullpage = v }
}

type ScreenshotArgsList []*ScreenshotArgs

func (s *ScreenshotArgsList) Len() int             { return len(*s) }
func (s *ScreenshotArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *ScreenshotArgsList) Append() model.Fielder  { v := &ScreenshotArgs{}; *s = append(*s, v); return v }
func (s *ScreenshotArgsList) IsNil() bool          { return s == nil }
func (s *ScreenshotArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *ScreenshotArgsList) DecodeFields(_ model.FieldReader) {}

func (m *ScreenshotArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type ClickElementArgs struct {
	Selector string
	WaitAfter int64
	Timeout int64
}

func (m *ClickElementArgs) ModelName() string { return "click_element_args" }

func (m *ClickElementArgs) Schema() []model.Field { return ClickElementArgsModel.Fields }

func (m *ClickElementArgs) Pointers() []any { return []any{&m.Selector, &m.WaitAfter, &m.Timeout} }

func (m *ClickElementArgs) IsNil() bool { return m == nil }

func (m *ClickElementArgs) EncodeFields(w model.FieldWriter) {
	w.String("selector", m.Selector)
	w.Int("wait_after", m.WaitAfter)
	w.Int("timeout", m.Timeout)
}

func (m *ClickElementArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("selector"); ok { m.Selector = v }
	if v, ok := r.Int("wait_after"); ok { m.WaitAfter = v }
	if v, ok := r.Int("timeout"); ok { m.Timeout = v }
}

type ClickElementArgsList []*ClickElementArgs

func (s *ClickElementArgsList) Len() int             { return len(*s) }
func (s *ClickElementArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *ClickElementArgsList) Append() model.Fielder  { v := &ClickElementArgs{}; *s = append(*s, v); return v }
func (s *ClickElementArgsList) IsNil() bool          { return s == nil }
func (s *ClickElementArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *ClickElementArgsList) DecodeFields(_ model.FieldReader) {}

func (m *ClickElementArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type NavigateArgs struct {
	Url string
}

func (m *NavigateArgs) ModelName() string { return "navigate_args" }

func (m *NavigateArgs) Schema() []model.Field { return NavigateArgsModel.Fields }

func (m *NavigateArgs) Pointers() []any { return []any{&m.Url} }

func (m *NavigateArgs) IsNil() bool { return m == nil }

func (m *NavigateArgs) EncodeFields(w model.FieldWriter) {
	w.String("url", m.Url)
}

func (m *NavigateArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("url"); ok { m.Url = v }
}

type NavigateArgsList []*NavigateArgs

func (s *NavigateArgsList) Len() int             { return len(*s) }
func (s *NavigateArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *NavigateArgsList) Append() model.Fielder  { v := &NavigateArgs{}; *s = append(*s, v); return v }
func (s *NavigateArgsList) IsNil() bool          { return s == nil }
func (s *NavigateArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *NavigateArgsList) DecodeFields(_ model.FieldReader) {}

func (m *NavigateArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type EmulateDeviceArgs struct {
	Mode string
	Device string
	Capture bool
	Selector string
}

func (m *EmulateDeviceArgs) ModelName() string { return "emulate_device_args" }

func (m *EmulateDeviceArgs) Schema() []model.Field { return EmulateDeviceArgsModel.Fields }

func (m *EmulateDeviceArgs) Pointers() []any { return []any{&m.Mode, &m.Device, &m.Capture, &m.Selector} }

func (m *EmulateDeviceArgs) IsNil() bool { return m == nil }

func (m *EmulateDeviceArgs) EncodeFields(w model.FieldWriter) {
	w.String("mode", m.Mode)
	w.String("device", m.Device)
	w.Bool("capture", m.Capture)
	w.String("selector", m.Selector)
}

func (m *EmulateDeviceArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("mode"); ok { m.Mode = v }
	if v, ok := r.String("device"); ok { m.Device = v }
	if v, ok := r.Bool("capture"); ok { m.Capture = v }
	if v, ok := r.String("selector"); ok { m.Selector = v }
}

type EmulateDeviceArgsList []*EmulateDeviceArgs

func (s *EmulateDeviceArgsList) Len() int             { return len(*s) }
func (s *EmulateDeviceArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *EmulateDeviceArgsList) Append() model.Fielder  { v := &EmulateDeviceArgs{}; *s = append(*s, v); return v }
func (s *EmulateDeviceArgsList) IsNil() bool          { return s == nil }
func (s *EmulateDeviceArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *EmulateDeviceArgsList) DecodeFields(_ model.FieldReader) {}

func (m *EmulateDeviceArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type AuditMobileArgs struct {
	Selector string
}

func (m *AuditMobileArgs) ModelName() string { return "audit_mobile_args" }

func (m *AuditMobileArgs) Schema() []model.Field { return AuditMobileArgsModel.Fields }

func (m *AuditMobileArgs) Pointers() []any { return []any{&m.Selector} }

func (m *AuditMobileArgs) IsNil() bool { return m == nil }

func (m *AuditMobileArgs) EncodeFields(w model.FieldWriter) {
	w.String("selector", m.Selector)
}

func (m *AuditMobileArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("selector"); ok { m.Selector = v }
}

type AuditMobileArgsList []*AuditMobileArgs

func (s *AuditMobileArgsList) Len() int             { return len(*s) }
func (s *AuditMobileArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *AuditMobileArgsList) Append() model.Fielder  { v := &AuditMobileArgs{}; *s = append(*s, v); return v }
func (s *AuditMobileArgsList) IsNil() bool          { return s == nil }
func (s *AuditMobileArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *AuditMobileArgsList) DecodeFields(_ model.FieldReader) {}

func (m *AuditMobileArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type GetConsoleArgs struct {
	Lines int64
}

func (m *GetConsoleArgs) ModelName() string { return "get_console_args" }

func (m *GetConsoleArgs) Schema() []model.Field { return GetConsoleArgsModel.Fields }

func (m *GetConsoleArgs) Pointers() []any { return []any{&m.Lines} }

func (m *GetConsoleArgs) IsNil() bool { return m == nil }

func (m *GetConsoleArgs) EncodeFields(w model.FieldWriter) {
	w.Int("lines", m.Lines)
}

func (m *GetConsoleArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.Int("lines"); ok { m.Lines = v }
}

type GetConsoleArgsList []*GetConsoleArgs

func (s *GetConsoleArgsList) Len() int             { return len(*s) }
func (s *GetConsoleArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *GetConsoleArgsList) Append() model.Fielder  { v := &GetConsoleArgs{}; *s = append(*s, v); return v }
func (s *GetConsoleArgsList) IsNil() bool          { return s == nil }
func (s *GetConsoleArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *GetConsoleArgsList) DecodeFields(_ model.FieldReader) {}

func (m *GetConsoleArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type FillElementArgs struct {
	Selector string
	Value string
	WaitAfter int64
	Timeout int64
}

func (m *FillElementArgs) ModelName() string { return "fill_element_args" }

func (m *FillElementArgs) Schema() []model.Field { return FillElementArgsModel.Fields }

func (m *FillElementArgs) Pointers() []any { return []any{&m.Selector, &m.Value, &m.WaitAfter, &m.Timeout} }

func (m *FillElementArgs) IsNil() bool { return m == nil }

func (m *FillElementArgs) EncodeFields(w model.FieldWriter) {
	w.String("selector", m.Selector)
	w.String("value", m.Value)
	w.Int("wait_after", m.WaitAfter)
	w.Int("timeout", m.Timeout)
}

func (m *FillElementArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("selector"); ok { m.Selector = v }
	if v, ok := r.String("value"); ok { m.Value = v }
	if v, ok := r.Int("wait_after"); ok { m.WaitAfter = v }
	if v, ok := r.Int("timeout"); ok { m.Timeout = v }
}

type FillElementArgsList []*FillElementArgs

func (s *FillElementArgsList) Len() int             { return len(*s) }
func (s *FillElementArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *FillElementArgsList) Append() model.Fielder  { v := &FillElementArgs{}; *s = append(*s, v); return v }
func (s *FillElementArgsList) IsNil() bool          { return s == nil }
func (s *FillElementArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *FillElementArgsList) DecodeFields(_ model.FieldReader) {}

func (m *FillElementArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type SwipeElementArgs struct {
	Selector string
	Direction string
	Distance int64
}

func (m *SwipeElementArgs) ModelName() string { return "swipe_element_args" }

func (m *SwipeElementArgs) Schema() []model.Field { return SwipeElementArgsModel.Fields }

func (m *SwipeElementArgs) Pointers() []any { return []any{&m.Selector, &m.Direction, &m.Distance} }

func (m *SwipeElementArgs) IsNil() bool { return m == nil }

func (m *SwipeElementArgs) EncodeFields(w model.FieldWriter) {
	w.String("selector", m.Selector)
	w.String("direction", m.Direction)
	w.Int("distance", m.Distance)
}

func (m *SwipeElementArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("selector"); ok { m.Selector = v }
	if v, ok := r.String("direction"); ok { m.Direction = v }
	if v, ok := r.Int("distance"); ok { m.Distance = v }
}

type SwipeElementArgsList []*SwipeElementArgs

func (s *SwipeElementArgsList) Len() int             { return len(*s) }
func (s *SwipeElementArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *SwipeElementArgsList) Append() model.Fielder  { v := &SwipeElementArgs{}; *s = append(*s, v); return v }
func (s *SwipeElementArgsList) IsNil() bool          { return s == nil }
func (s *SwipeElementArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *SwipeElementArgsList) DecodeFields(_ model.FieldReader) {}

func (m *SwipeElementArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type EvaluateJSArgs struct {
	Script string
	AwaitPromise bool
}

func (m *EvaluateJSArgs) ModelName() string { return "evaluate_js_args" }

func (m *EvaluateJSArgs) Schema() []model.Field { return EvaluateJSArgsModel.Fields }

func (m *EvaluateJSArgs) Pointers() []any { return []any{&m.Script, &m.AwaitPromise} }

func (m *EvaluateJSArgs) IsNil() bool { return m == nil }

func (m *EvaluateJSArgs) EncodeFields(w model.FieldWriter) {
	w.String("script", m.Script)
	w.Bool("await_promise", m.AwaitPromise)
}

func (m *EvaluateJSArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("script"); ok { m.Script = v }
	if v, ok := r.Bool("await_promise"); ok { m.AwaitPromise = v }
}

type EvaluateJSArgsList []*EvaluateJSArgs

func (s *EvaluateJSArgsList) Len() int             { return len(*s) }
func (s *EvaluateJSArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *EvaluateJSArgsList) Append() model.Fielder  { v := &EvaluateJSArgs{}; *s = append(*s, v); return v }
func (s *EvaluateJSArgsList) IsNil() bool          { return s == nil }
func (s *EvaluateJSArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *EvaluateJSArgsList) DecodeFields(_ model.FieldReader) {}

func (m *EvaluateJSArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type GetNetworkLogsArgs struct {
	Filter string
	Limit int64
}

func (m *GetNetworkLogsArgs) ModelName() string { return "get_network_logs_args" }

func (m *GetNetworkLogsArgs) Schema() []model.Field { return GetNetworkLogsArgsModel.Fields }

func (m *GetNetworkLogsArgs) Pointers() []any { return []any{&m.Filter, &m.Limit} }

func (m *GetNetworkLogsArgs) IsNil() bool { return m == nil }

func (m *GetNetworkLogsArgs) EncodeFields(w model.FieldWriter) {
	w.String("filter", m.Filter)
	w.Int("limit", m.Limit)
}

func (m *GetNetworkLogsArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("filter"); ok { m.Filter = v }
	if v, ok := r.Int("limit"); ok { m.Limit = v }
}

type GetNetworkLogsArgsList []*GetNetworkLogsArgs

func (s *GetNetworkLogsArgsList) Len() int             { return len(*s) }
func (s *GetNetworkLogsArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *GetNetworkLogsArgsList) Append() model.Fielder  { v := &GetNetworkLogsArgs{}; *s = append(*s, v); return v }
func (s *GetNetworkLogsArgsList) IsNil() bool          { return s == nil }
func (s *GetNetworkLogsArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *GetNetworkLogsArgsList) DecodeFields(_ model.FieldReader) {}

func (m *GetNetworkLogsArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type GetErrorsArgs struct {
	Limit int64
}

func (m *GetErrorsArgs) ModelName() string { return "get_errors_args" }

func (m *GetErrorsArgs) Schema() []model.Field { return GetErrorsArgsModel.Fields }

func (m *GetErrorsArgs) Pointers() []any { return []any{&m.Limit} }

func (m *GetErrorsArgs) IsNil() bool { return m == nil }

func (m *GetErrorsArgs) EncodeFields(w model.FieldWriter) {
	w.Int("limit", m.Limit)
}

func (m *GetErrorsArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.Int("limit"); ok { m.Limit = v }
}

type GetErrorsArgsList []*GetErrorsArgs

func (s *GetErrorsArgsList) Len() int             { return len(*s) }
func (s *GetErrorsArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *GetErrorsArgsList) Append() model.Fielder  { v := &GetErrorsArgs{}; *s = append(*s, v); return v }
func (s *GetErrorsArgsList) IsNil() bool          { return s == nil }
func (s *GetErrorsArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *GetErrorsArgsList) DecodeFields(_ model.FieldReader) {}

func (m *GetErrorsArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type GetPerformanceArgs struct {
}

func (m *GetPerformanceArgs) ModelName() string { return "get_performance_args" }

func (m *GetPerformanceArgs) Schema() []model.Field { return GetPerformanceArgsModel.Fields }

func (m *GetPerformanceArgs) Pointers() []any { return []any{} }

func (m *GetPerformanceArgs) IsNil() bool { return m == nil }

func (m *GetPerformanceArgs) EncodeFields(w model.FieldWriter) {
}

func (m *GetPerformanceArgs) DecodeFields(r model.FieldReader) {
}

type GetPerformanceArgsList []*GetPerformanceArgs

func (s *GetPerformanceArgsList) Len() int             { return len(*s) }
func (s *GetPerformanceArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *GetPerformanceArgsList) Append() model.Fielder  { v := &GetPerformanceArgs{}; *s = append(*s, v); return v }
func (s *GetPerformanceArgsList) IsNil() bool          { return s == nil }
func (s *GetPerformanceArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *GetPerformanceArgsList) DecodeFields(_ model.FieldReader) {}

func (m *GetPerformanceArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type GetContentArgs struct {
}

func (m *GetContentArgs) ModelName() string { return "get_content_args" }

func (m *GetContentArgs) Schema() []model.Field { return GetContentArgsModel.Fields }

func (m *GetContentArgs) Pointers() []any { return []any{} }

func (m *GetContentArgs) IsNil() bool { return m == nil }

func (m *GetContentArgs) EncodeFields(w model.FieldWriter) {
}

func (m *GetContentArgs) DecodeFields(r model.FieldReader) {
}

type GetContentArgsList []*GetContentArgs

func (s *GetContentArgsList) Len() int             { return len(*s) }
func (s *GetContentArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *GetContentArgsList) Append() model.Fielder  { v := &GetContentArgs{}; *s = append(*s, v); return v }
func (s *GetContentArgsList) IsNil() bool          { return s == nil }
func (s *GetContentArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *GetContentArgsList) DecodeFields(_ model.FieldReader) {}

func (m *GetContentArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type GetSourceArgs struct {
	Selector string
}

func (m *GetSourceArgs) ModelName() string { return "get_source_args" }

func (m *GetSourceArgs) Schema() []model.Field { return GetSourceArgsModel.Fields }

func (m *GetSourceArgs) Pointers() []any { return []any{&m.Selector} }

func (m *GetSourceArgs) IsNil() bool { return m == nil }

func (m *GetSourceArgs) EncodeFields(w model.FieldWriter) {
	w.String("selector", m.Selector)
}

func (m *GetSourceArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("selector"); ok { m.Selector = v }
}

type GetSourceArgsList []*GetSourceArgs

func (s *GetSourceArgsList) Len() int             { return len(*s) }
func (s *GetSourceArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *GetSourceArgsList) Append() model.Fielder  { v := &GetSourceArgs{}; *s = append(*s, v); return v }
func (s *GetSourceArgsList) IsNil() bool          { return s == nil }
func (s *GetSourceArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *GetSourceArgsList) DecodeFields(_ model.FieldReader) {}

func (m *GetSourceArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type InspectElementArgs struct {
	Selector string
}

func (m *InspectElementArgs) ModelName() string { return "inspect_element_args" }

func (m *InspectElementArgs) Schema() []model.Field { return InspectElementArgsModel.Fields }

func (m *InspectElementArgs) Pointers() []any { return []any{&m.Selector} }

func (m *InspectElementArgs) IsNil() bool { return m == nil }

func (m *InspectElementArgs) EncodeFields(w model.FieldWriter) {
	w.String("selector", m.Selector)
}

func (m *InspectElementArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("selector"); ok { m.Selector = v }
}

type InspectElementArgsList []*InspectElementArgs

func (s *InspectElementArgsList) Len() int             { return len(*s) }
func (s *InspectElementArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *InspectElementArgsList) Append() model.Fielder  { v := &InspectElementArgs{}; *s = append(*s, v); return v }
func (s *InspectElementArgsList) IsNil() bool          { return s == nil }
func (s *InspectElementArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *InspectElementArgsList) DecodeFields(_ model.FieldReader) {}

func (m *InspectElementArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type GetStylesArgs struct {
	Selector string
	Sheet int64
}

func (m *GetStylesArgs) ModelName() string { return "get_styles_args" }

func (m *GetStylesArgs) Schema() []model.Field { return GetStylesArgsModel.Fields }

func (m *GetStylesArgs) Pointers() []any { return []any{&m.Selector, &m.Sheet} }

func (m *GetStylesArgs) IsNil() bool { return m == nil }

func (m *GetStylesArgs) EncodeFields(w model.FieldWriter) {
	w.String("selector", m.Selector)
	w.Int("sheet", m.Sheet)
}

func (m *GetStylesArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("selector"); ok { m.Selector = v }
	if v, ok := r.Int("sheet"); ok { m.Sheet = v }
}

type GetStylesArgsList []*GetStylesArgs

func (s *GetStylesArgsList) Len() int             { return len(*s) }
func (s *GetStylesArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *GetStylesArgsList) Append() model.Fielder  { v := &GetStylesArgs{}; *s = append(*s, v); return v }
func (s *GetStylesArgsList) IsNil() bool          { return s == nil }
func (s *GetStylesArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *GetStylesArgsList) DecodeFields(_ model.FieldReader) {}

func (m *GetStylesArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type GetStorageArgs struct {
	Type string
}

func (m *GetStorageArgs) ModelName() string { return "get_storage_args" }

func (m *GetStorageArgs) Schema() []model.Field { return GetStorageArgsModel.Fields }

func (m *GetStorageArgs) Pointers() []any { return []any{&m.Type} }

func (m *GetStorageArgs) IsNil() bool { return m == nil }

func (m *GetStorageArgs) EncodeFields(w model.FieldWriter) {
	w.String("type", m.Type)
}

func (m *GetStorageArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("type"); ok { m.Type = v }
}

type GetStorageArgsList []*GetStorageArgs

func (s *GetStorageArgsList) Len() int             { return len(*s) }
func (s *GetStorageArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *GetStorageArgsList) Append() model.Fielder  { v := &GetStorageArgs{}; *s = append(*s, v); return v }
func (s *GetStorageArgsList) IsNil() bool          { return s == nil }
func (s *GetStorageArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *GetStorageArgsList) DecodeFields(_ model.FieldReader) {}

func (m *GetStorageArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type GetAssetArgs struct {
	Url string
}

func (m *GetAssetArgs) ModelName() string { return "get_asset_args" }

func (m *GetAssetArgs) Schema() []model.Field { return GetAssetArgsModel.Fields }

func (m *GetAssetArgs) Pointers() []any { return []any{&m.Url} }

func (m *GetAssetArgs) IsNil() bool { return m == nil }

func (m *GetAssetArgs) EncodeFields(w model.FieldWriter) {
	w.String("url", m.Url)
}

func (m *GetAssetArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("url"); ok { m.Url = v }
}

type GetAssetArgsList []*GetAssetArgs

func (s *GetAssetArgsList) Len() int             { return len(*s) }
func (s *GetAssetArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *GetAssetArgsList) Append() model.Fielder  { v := &GetAssetArgs{}; *s = append(*s, v); return v }
func (s *GetAssetArgsList) IsNil() bool          { return s == nil }
func (s *GetAssetArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *GetAssetArgsList) DecodeFields(_ model.FieldReader) {}

func (m *GetAssetArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type InterceptRequestArgs struct {
	Action string
	Filter string
	Limit int64
}

func (m *InterceptRequestArgs) ModelName() string { return "intercept_request_args" }

func (m *InterceptRequestArgs) Schema() []model.Field { return InterceptRequestArgsModel.Fields }

func (m *InterceptRequestArgs) Pointers() []any { return []any{&m.Action, &m.Filter, &m.Limit} }

func (m *InterceptRequestArgs) IsNil() bool { return m == nil }

func (m *InterceptRequestArgs) EncodeFields(w model.FieldWriter) {
	w.String("action", m.Action)
	w.String("filter", m.Filter)
	w.Int("limit", m.Limit)
}

func (m *InterceptRequestArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("action"); ok { m.Action = v }
	if v, ok := r.String("filter"); ok { m.Filter = v }
	if v, ok := r.Int("limit"); ok { m.Limit = v }
}

type InterceptRequestArgsList []*InterceptRequestArgs

func (s *InterceptRequestArgsList) Len() int             { return len(*s) }
func (s *InterceptRequestArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *InterceptRequestArgsList) Append() model.Fielder  { v := &InterceptRequestArgs{}; *s = append(*s, v); return v }
func (s *InterceptRequestArgsList) IsNil() bool          { return s == nil }
func (s *InterceptRequestArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *InterceptRequestArgsList) DecodeFields(_ model.FieldReader) {}

func (m *InterceptRequestArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type OpenBrowserArgs struct {
	Port string
	Https bool
}

func (m *OpenBrowserArgs) ModelName() string { return "open_browser_args" }

func (m *OpenBrowserArgs) Schema() []model.Field { return OpenBrowserArgsModel.Fields }

func (m *OpenBrowserArgs) Pointers() []any { return []any{&m.Port, &m.Https} }

func (m *OpenBrowserArgs) IsNil() bool { return m == nil }

func (m *OpenBrowserArgs) EncodeFields(w model.FieldWriter) {
	w.String("port", m.Port)
	w.Bool("https", m.Https)
}

func (m *OpenBrowserArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("port"); ok { m.Port = v }
	if v, ok := r.Bool("https"); ok { m.Https = v }
}

type OpenBrowserArgsList []*OpenBrowserArgs

func (s *OpenBrowserArgsList) Len() int             { return len(*s) }
func (s *OpenBrowserArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *OpenBrowserArgsList) Append() model.Fielder  { v := &OpenBrowserArgs{}; *s = append(*s, v); return v }
func (s *OpenBrowserArgsList) IsNil() bool          { return s == nil }
func (s *OpenBrowserArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *OpenBrowserArgsList) DecodeFields(_ model.FieldReader) {}

func (m *OpenBrowserArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type CloseBrowserArgs struct {
}

func (m *CloseBrowserArgs) ModelName() string { return "close_browser_args" }

func (m *CloseBrowserArgs) Schema() []model.Field { return CloseBrowserArgsModel.Fields }

func (m *CloseBrowserArgs) Pointers() []any { return []any{} }

func (m *CloseBrowserArgs) IsNil() bool { return m == nil }

func (m *CloseBrowserArgs) EncodeFields(w model.FieldWriter) {
}

func (m *CloseBrowserArgs) DecodeFields(r model.FieldReader) {
}

type CloseBrowserArgsList []*CloseBrowserArgs

func (s *CloseBrowserArgsList) Len() int             { return len(*s) }
func (s *CloseBrowserArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *CloseBrowserArgsList) Append() model.Fielder  { v := &CloseBrowserArgs{}; *s = append(*s, v); return v }
func (s *CloseBrowserArgsList) IsNil() bool          { return s == nil }
func (s *CloseBrowserArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *CloseBrowserArgsList) DecodeFields(_ model.FieldReader) {}

func (m *CloseBrowserArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type SaveScreenshotArgs struct {
	Dir string
	Name string
	Selector string
	Fullpage bool
	Overwrite bool
}

func (m *SaveScreenshotArgs) ModelName() string { return "save_screenshot_args" }

func (m *SaveScreenshotArgs) Schema() []model.Field { return SaveScreenshotArgsModel.Fields }

func (m *SaveScreenshotArgs) Pointers() []any { return []any{&m.Dir, &m.Name, &m.Selector, &m.Fullpage, &m.Overwrite} }

func (m *SaveScreenshotArgs) IsNil() bool { return m == nil }

func (m *SaveScreenshotArgs) EncodeFields(w model.FieldWriter) {
	w.String("dir", m.Dir)
	w.String("name", m.Name)
	w.String("selector", m.Selector)
	w.Bool("fullpage", m.Fullpage)
	w.Bool("overwrite", m.Overwrite)
}

func (m *SaveScreenshotArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("dir"); ok { m.Dir = v }
	if v, ok := r.String("name"); ok { m.Name = v }
	if v, ok := r.String("selector"); ok { m.Selector = v }
	if v, ok := r.Bool("fullpage"); ok { m.Fullpage = v }
	if v, ok := r.Bool("overwrite"); ok { m.Overwrite = v }
}

type SaveScreenshotArgsList []*SaveScreenshotArgs

func (s *SaveScreenshotArgsList) Len() int             { return len(*s) }
func (s *SaveScreenshotArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *SaveScreenshotArgsList) Append() model.Fielder  { v := &SaveScreenshotArgs{}; *s = append(*s, v); return v }
func (s *SaveScreenshotArgsList) IsNil() bool          { return s == nil }
func (s *SaveScreenshotArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *SaveScreenshotArgsList) DecodeFields(_ model.FieldReader) {}

func (m *SaveScreenshotArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

